/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#faf8ff",
        surface: "#faf8ff",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#3323cc",
        "surface-dim": "#d2d9f4",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#dae2fd",
        "on-surface-variant": "#464555",
        "on-tertiary-fixed-variant": "#444749",
        primary: "#3525cd",
        "surface-container": "#eaedff",
        "surface-container-low": "#f2f3ff",
        "surface-container-high": "#e2e7ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-container": "#dad7ff",
        "on-secondary-fixed-variant": "#004e5c",
        "error-container": "#ffdad6",
        "tertiary-container": "#5e6163",
        "on-primary": "#ffffff",
        "primary-container": "#4f46e5",
        "secondary-fixed": "#acedff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-container": "#dadcde",
        background: "#faf8ff",
        "inverse-surface": "#283044",
        "on-secondary-container": "#006172",
        "secondary-container": "#57dffe",
        "on-secondary": "#ffffff",
        "on-surface": "#131b2e",
        "on-background": "#131b2e",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed": "#001f26",
        tertiary: "#46494b",
        outline: "#777587",
        "on-primary-fixed": "#0f0069",
        secondary: "#00687a",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface-tint": "#4d44e3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "24px",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1280px",
        unit: "8px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
      },
    },
  },
  plugins: [],
}